#if !LITE_BUILD
import Foundation

/// App-bundled clean-room equivalents of the small Wallpaper Engine framework
/// files referenced by common scene projects. These files were authored
/// locally and contain no WPE bytes; they ship as normal bundle resources
/// under `wpe-builtins/` (total ~68 KB).
///
/// The bundled set:
/// - `materials/effects/refractnormal.png`
/// - `materials/effects/waterflowphase.png`
/// - `materials/effects/waterripplenormal.png`
/// - `materials/util/black.png`
/// - `materials/util/clouds_256.png`
/// - `materials/util/composelayer.json`
/// - `materials/util/effectcomposebackground.json`
/// - `materials/util/flatnormal.png`
/// - `materials/util/fullscreenlayer.json`
/// - `materials/util/noise.png`
/// - `materials/util/solidlayer.json`
/// - `materials/util/solidlayer_depthtest.json`
/// - `materials/util/solidlayer_instance.json`
/// - `materials/util/solidlayer_instance_4.json`
/// - `materials/util/white.png`
/// - `models/util/composelayer.json`
/// - `models/util/fullscreenlayer.json`
/// - `models/util/projectlayer.json`
/// - `models/util/solidlayer.json`
/// - `models/util/solidlayer_depthtest.json`
///
/// Why this exists: WPE doesn't run on macOS, so the user can't generally
/// grant their Wallpaper Engine install folder as a runtime fallback. The
/// bundled set gives most scenes zero-config coverage. A user-granted WPE
/// folder remains available as an advanced fallback for the rare scene that
/// references files outside this inventory.
///
/// The PNG noise textures are generated by `scripts/generate-wpe-builtin-noise.py`
/// using a seeded Perlin variant — re-running the script is idempotent.
enum WPEBuiltinFrameworkAssets {
    /// Bundle directory containing the resources. The `.bundle` extension
    /// tells Xcode to copy the directory verbatim (subdirectories intact)
    /// rather than flatten files into the bundle root, which would collide
    /// `models/util/composelayer.json` with `materials/util/composelayer.json`.
    /// `nil` only in test bundles that don't ship the resource subtree.
    static let rootURL: URL? = Bundle.main.url(
        forResource: "wpe-builtins",
        withExtension: "bundle"
    )

    /// Builds a `SceneResourceResolver` rooted at `rootURL`.
    static func makeResolver() -> SceneResourceResolver? {
        guard let rootURL else { return nil }
        return SceneResourceResolver(cacheRootURL: rootURL)
    }

    /// Every file the bundle ships. Test code iterates this list to verify
    /// the bundle subtree shipped intact. If you add a new file under
    /// `LiveWallpaper/Resources/wpe-builtins/`, append the relative path
    /// here so the test covers it.
    static let expectedFiles: [String] = [
        "materials/effects/refractnormal.png",
        "materials/effects/waterflowphase.png",
        "materials/effects/waterripplenormal.png",
        "materials/util/black.png",
        "materials/util/clouds_256.png",
        "materials/util/composelayer.json",
        "materials/util/effectcomposebackground.json",
        "materials/util/flatnormal.png",
        "materials/util/fullscreenlayer.json",
        "materials/util/noise.png",
        "materials/util/solidlayer.json",
        "materials/util/solidlayer_depthtest.json",
        "materials/util/solidlayer_instance.json",
        "materials/util/solidlayer_instance_4.json",
        "materials/util/white.png",
        "models/util/composelayer.json",
        "models/util/fullscreenlayer.json",
        "models/util/projectlayer.json",
        "models/util/solidlayer.json",
        "models/util/solidlayer_depthtest.json"
    ]
}
#endif
